services:
  db:
    image: mariadb:10.8.3
    container_name: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/db:/var/lib/mysql
    networks:
      - app-laravel

  app:
    build:
      context: .
      dockerfile: .docker/docker_images/dockerfile.laravel
    container_name: app
    restart: always
    working_dir: /var/www/html/app
    volumes:
      - .:/var/www/html/app
    depends_on:
      - db
    networks:
      - app-laravel

  nginx:
    image: alan01777/nginx-laravel:1.0.0
    container_name: nginx
    restart: always
    working_dir: /var/www/html/app
    volumes:
      - .docker/nginx/log:/var/log/nginx
      - .:/var/www/html/app
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-laravel

networks:
  app-laravel:
    driver: bridge
