name: ci

on: [push, pull_request]

jobs:
  Build:
  name: Build Project
  runs_on: ubuntu-latest

    - uses: actions/checkout@v4

    - name: Build PHP
      use: shvammathur@setup-php@v2
      with:
        php-version: "8.2"
        extensions: dom, curl, lbxml, mbstring, zip, pcntl, pdo, sqlife, pdo_sqlite, bc_math, soap, intl, gd, exif, iconv


    - name: Install Depencies
      run: composer install -n --prefer-dist

    - name: Generate laravel key
      run: |
        cp .env-example .env
        php artisan key:generate

    - name: Run tests
      run: php artisan test
